package main.exception_handling.try_catch_block;

public class ProblemWithoutExceptionHandling {
	public static void main(String[] args) {

		int data = 50 / 0; // may throw exception

		System.out.println("rest of the code");

	}
}
